/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_api_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Item
         * @description Правка полей. Машинная версия сохраняется, правка не затирается (FR-042, FR-043).
         */
        patch: operations["patch_item_api_items__item_id__patch"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Item
         * @description Ручное добавление материала — FR-009. Проходит ту же обработку, что собранное.
         */
        post: operations["create_item_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Assessment
         * @description Правка баллов с немедленным пересчётом индекса — FR-041.
         *
         *     Пользователь исправляет один балл, а не отвергает оценку целиком. Каждая такая
         *     правка — эталонная метка: расхождение машина/человек пополняет eval-датасет.
         */
        patch: operations["patch_assessment_api_items__item_id__assessment_patch"];
        trace?: never;
    };
    "/api/items/{item_id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hide Item
         * @description Скрытие обратимо — FR-045. Причина сохраняется: без неё сигнал бесполезен
         *     для последующего тюнинга порогов.
         */
        post: operations["hide_item_api_items__item_id__hide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/track-as-act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track As Act */
        post: operations["track_as_act_api_items__item_id__track_as_act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Acts */
        get: operations["list_acts_api_acts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acts/{act_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Act */
        get: operations["get_act_api_acts__act_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Act
         * @description Смена стадии и архивация — FR-032, FR-037.
         *
         *     Смена стадии порождает событие хронологии и помечает досье к переоценке
         *     (FR-034): документ, который раньше затрагивал компанию, после новой стадии
         *     может затрагивать её иначе.
         */
        patch: operations["patch_act_api_acts__act_id__patch"];
        trace?: never;
    };
    "/api/acts/{act_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Act Event
         * @description Добавить событие в хронологию — FR-033.
         *
         *     Каждое событие ссылается на документ или материал-основание: так версии,
         *     отзывы и слушания становятся узлами одной хронологии, а не отдельными вкладками.
         */
        post: operations["add_act_event_api_acts__act_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acts/{act_id}/link-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Item
         * @description Связать поступивший материал с существующим досье — FR-036.
         */
        post: operations["link_item_api_acts__act_id__link_item_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Удаление источника не удаляет собранные материалы — FR-004.
         */
        delete: operations["delete_source_api_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_api_sources__source_id__patch"];
        trace?: never;
    };
    "/api/sources/{source_id}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Collect Now
         * @description Немедленный запуск сбора — нужен на демонстрации, чтобы не ждать расписания.
         */
        post: operations["collect_now_api_sources__source_id__collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Profile */
        post: operations["activate_profile_api_profiles__profile_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story
         * @description Карточка события: все источники и ссылки на оригиналы.
         */
        get: operations["get_story_api_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Split Cluster
         * @description Разъединить ошибочно объединённый кластер — FR-062.
         */
        post: operations["split_cluster_api_stories__story_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Digests */
        get: operations["list_digests_api_digests_get"];
        put?: never;
        /** Create Digest */
        post: operations["create_digest_api_digests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digests/{digest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest */
        get: operations["get_digest_api_digests__digest_id__get"];
        put?: never;
        post?: never;
        /** Delete Digest */
        delete: operations["delete_digest_api_digests__digest_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digests/{digest_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Entry
         * @description Исключение материала из дайджеста не удаляет его из ленты — FR-071.
         *
         *     Один и тот же материал бывает полезен одному получателю и лишний другому,
         *     поэтому исключение локально для конкретного дайджеста.
         */
        patch: operations["toggle_entry_api_digests__digest_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/digests/{digest_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Digest
         * @description Выгрузка для отправки по почте — FR-072.
         *
         *     Ссылка на оригинал сохраняется у каждого материала: получатель должен иметь
         *     возможность проверить первоисточник, а не верить пересказу.
         */
        get: operations["export_digest_api_digests__digest_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActCardOut */
        ActCardOut: {
            /** Id */
            id: number;
            /** Act Identifier */
            act_identifier: string;
            /** Doc Type */
            doc_type: string;
            /** Stage */
            stage: string;
            /** Index Value */
            index_value?: number | null;
            /** Final Category */
            final_category?: string | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Effective From */
            effective_from?: string | null;
            /**
             * Essence
             * @default
             */
            essence: string;
            /**
             * Timeline Count
             * @default 0
             */
            timeline_count: number;
            /**
             * Linked Count
             * @default 0
             */
            linked_count: number;
        };
        /** ActDetailOut */
        ActDetailOut: {
            /** Id */
            id: number;
            /** Act Identifier */
            act_identifier: string;
            /** Doc Type */
            doc_type: string;
            /** Stage */
            stage: string;
            /** Index Value */
            index_value?: number | null;
            /** Final Category */
            final_category?: string | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Is Archived */
            is_archived: boolean;
            /** Effective From */
            effective_from?: string | null;
            /**
             * Essence
             * @default
             */
            essence: string;
            /**
             * Timeline Count
             * @default 0
             */
            timeline_count: number;
            /**
             * Linked Count
             * @default 0
             */
            linked_count: number;
            /** Source Url */
            source_url: string;
            /** Timeline */
            timeline?: components["schemas"]["ActEventOut"][];
            /** Assessment History */
            assessment_history?: components["schemas"]["AssessmentOut"][];
            /** Linked Items */
            linked_items?: components["schemas"]["ItemCardOut"][];
        };
        /**
         * ActEventCreate
         * @description Событие хронологии — FR-033.
         */
        ActEventCreate: {
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date
             */
            occurred_at: string;
            /** Description */
            description: string;
            /** Version Label */
            version_label?: string | null;
            /** Document Url */
            document_url?: string | null;
            /** Source Item Id */
            source_item_id?: number | null;
        };
        /** ActEventOut */
        ActEventOut: {
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date
             */
            occurred_at: string;
            /** Description */
            description: string;
            /** Version Label */
            version_label?: string | null;
            /** Document Url */
            document_url?: string | null;
            /** Source Item Id */
            source_item_id?: number | null;
        };
        /**
         * ActPatch
         * @description Смена стадии и архивация досье — FR-032, FR-034, FR-037.
         */
        ActPatch: {
            /** Stage */
            stage?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
            /** Is Tracked */
            is_tracked?: boolean | null;
            /** Effective From */
            effective_from?: string | null;
            /** Essence */
            essence?: string | null;
            /** Doc Type */
            doc_type?: string | null;
            /** Position */
            position?: string | null;
            /** Owner */
            owner?: string | null;
        };
        /** AssessmentOut */
        AssessmentOut: {
            /** Scheme */
            scheme: string;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Rationales */
            rationales: {
                [key: string]: string;
            };
            /** Breakdown */
            breakdown?: components["schemas"]["CriterionScoreOut"][];
            /** Index Value */
            index_value: number;
            /** Category */
            category: string;
            /** Escalation Flags */
            escalation_flags?: string[];
            /** Final Category */
            final_category: string;
            /**
             * Escalated
             * @default false
             */
            escalated: boolean;
            /** Author */
            author: string;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AssessmentPatch
         * @description Правка баллов с немедленным пересчётом индекса — FR-041.
         */
        AssessmentPatch: {
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Escalation Flags */
            escalation_flags?: string[] | null;
        };
        /**
         * ClaimOut
         * @description Заземление утверждения — FR-025.
         */
        ClaimOut: {
            /** Statement */
            statement: string;
            /** Quote */
            quote: string;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /** Quote Found */
            quote_found: boolean;
            /** Entailed */
            entailed?: boolean | null;
            /** Reject Reason */
            reject_reason?: string | null;
        };
        /**
         * CriterionScoreOut
         * @description Один критерий в разложении оценки — FR-024.
         */
        CriterionScoreOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Weight */
            weight: number;
            /** Contribution */
            contribution: number;
            /** Scale Label */
            scale_label: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /**
         * DigestCreate
         * @description Сборка дайджеста из отобранных материалов — FR-070.
         */
        DigestCreate: {
            /** Recipient */
            recipient: string;
            /** Title */
            title?: string | null;
            /** Item Ids */
            item_ids: number[];
        };
        /**
         * DigestEntryPatch
         * @description Исключение материала из дайджеста без удаления из ленты — FR-071.
         */
        DigestEntryPatch: {
            /** Is Excluded */
            is_excluded: boolean;
        };
        /** DigestItemOut */
        DigestItemOut: {
            /** Position */
            position: number;
            /** Is Excluded */
            is_excluded: boolean;
            item: components["schemas"]["ItemCardOut"];
        };
        /** DigestOut */
        DigestOut: {
            /** Id */
            id: number;
            /** Recipient */
            recipient: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entries */
            entries?: components["schemas"]["DigestItemOut"][];
        };
        /** EntitiesOut */
        EntitiesOut: {
            /** Who */
            who?: string[];
            /**
             * What
             * @default
             */
            what: string;
            /**
             * When
             * @default
             */
            when: string;
            /**
             * Consequences
             * @default
             */
            consequences: string;
        };
        /** FeedResponse */
        FeedResponse: {
            /** Items */
            items: components["schemas"]["ItemCardOut"][];
            /** Total */
            total: number;
        };
        /**
         * GroundingOut
         * @description Счётчик неподтверждённого — иначе молчаливое отбрасывание рождает недоверие.
         */
        GroundingOut: {
            /** Total */
            total: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** HideRequest */
        HideRequest: {
            /**
             * Hidden
             * @default true
             */
            hidden: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** ItemCardOut */
        ItemCardOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            entities: components["schemas"]["EntitiesOut"];
            /** Item Type */
            item_type: string;
            /** Topic */
            topic?: string | null;
            /** Index Value */
            index_value?: number | null;
            /** Final Category */
            final_category?: string | null;
            /** Escalation Flags */
            escalation_flags?: string[];
            /** Url */
            url: string;
            source: components["schemas"]["SourceRefOut"];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Published At Is Approx */
            published_at_is_approx: boolean;
            /** Is Partial Text */
            is_partial_text: boolean;
            /** Is Relevant */
            is_relevant?: boolean | null;
            /** Is Hidden */
            is_hidden: boolean;
            /** Is Edited */
            is_edited: boolean;
            /** Assessment Failed */
            assessment_failed: boolean;
            grounding?: components["schemas"]["GroundingOut"] | null;
            /** Story Id */
            story_id?: number | null;
            story?: components["schemas"]["StoryRefOut"] | null;
            /** Act Id */
            act_id?: number | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * ItemCreate
         * @description Ручное добавление материала — FR-009.
         */
        ItemCreate: {
            /** Title */
            title: string;
            /** Raw Text */
            raw_text: string;
            /** Url */
            url?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** ItemDetailOut */
        ItemDetailOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            entities: components["schemas"]["EntitiesOut"];
            /** Item Type */
            item_type: string;
            /** Topic */
            topic?: string | null;
            /** Index Value */
            index_value?: number | null;
            /** Final Category */
            final_category?: string | null;
            /** Escalation Flags */
            escalation_flags?: string[];
            /** Url */
            url: string;
            source: components["schemas"]["SourceRefOut"];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Published At Is Approx */
            published_at_is_approx: boolean;
            /** Is Partial Text */
            is_partial_text: boolean;
            /** Is Relevant */
            is_relevant?: boolean | null;
            /** Is Hidden */
            is_hidden: boolean;
            /** Is Edited */
            is_edited: boolean;
            /** Assessment Failed */
            assessment_failed: boolean;
            grounding?: components["schemas"]["GroundingOut"] | null;
            /** Story Id */
            story_id?: number | null;
            story?: components["schemas"]["StoryRefOut"] | null;
            /** Act Id */
            act_id?: number | null;
            /** Tags */
            tags?: string[];
            /** Raw Text */
            raw_text: string;
            /** Claims */
            claims?: components["schemas"]["ClaimOut"][];
            assessment?: components["schemas"]["AssessmentOut"] | null;
            /** User Note */
            user_note?: string | null;
            /** Revisions */
            revisions?: components["schemas"]["RevisionOut"][];
            /** Machine Summary */
            machine_summary?: string | null;
            machine_assessment?: components["schemas"]["AssessmentOut"] | null;
        };
        /**
         * ItemPatch
         * @description Правка полей материала — FR-040, FR-044.
         */
        ItemPatch: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Topic */
            topic?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** User Note */
            user_note?: string | null;
        };
        /**
         * LinkItemRequest
         * @description Связать материал с досье — FR-036.
         */
        LinkItemRequest: {
            /** Item Id */
            item_id: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Industry */
            industry: string;
            /** Products */
            products: string[];
            /** Regimes */
            regimes: string[];
            /** Risk Areas */
            risk_areas: string[];
            /** Growth Areas */
            growth_areas: string[];
            /** Competitors */
            competitors: string[];
            /** Noise Markers */
            noise_markers: string[];
            /** Is Active */
            is_active: boolean;
        };
        /** RevisionOut */
        RevisionOut: {
            /** Field */
            field: string;
            /** Old Value */
            old_value?: unknown | null;
            /** New Value */
            new_value?: unknown | null;
            /** Author */
            author: string;
            /** Reason */
            reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Type */
            type: string;
            /** Url */
            url: string;
            /** Title */
            title?: string | null;
            /** Category */
            category?: string | null;
            /** Item Type */
            item_type?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Item Type */
            item_type: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Is Active */
            is_active: boolean;
            /** Poll Interval Min */
            poll_interval_min: number;
            /** Last Polled At */
            last_polled_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
        };
        /** SourceRefOut */
        SourceRefOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Category */
            category: string;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Title */
            title?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Poll Interval Min */
            poll_interval_min?: number | null;
        };
        /** StoryMemberOut */
        StoryMemberOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            source: components["schemas"]["SourceRefOut"];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** StoryOut */
        StoryOut: {
            /** Id */
            id: number;
            /** Canonical Title */
            canonical_title: string;
            /** Fact Summary */
            fact_summary: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Item Count */
            item_count: number;
            /** Was Split By User */
            was_split_by_user: boolean;
            /** Items */
            items?: components["schemas"]["StoryMemberOut"][];
        };
        /** StoryRefOut */
        StoryRefOut: {
            /** Id */
            id: number;
            /** Item Count */
            item_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_feed_api_feed_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                source_id?: number | null;
                item_type?: string | null;
                topic?: string | null;
                category?: string | null;
                /** @description поиск по тексту, тегам и сущностям */
                q?: string | null;
                include_irrelevant?: boolean;
                include_hidden?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_item_api_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_assessment_api_items__item_id__assessment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_item_api_items__item_id__hide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_as_act_api_items__item_id__track_as_act_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_acts_api_acts_get: {
        parameters: {
            query?: {
                stage?: string | null;
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_act_api_acts__act_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_act_api_acts__act_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_act_event_api_acts__act_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_item_api_acts__act_id__link_item_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                act_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_api_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_now_api_sources__source_id__collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"][];
                };
            };
        };
    };
    activate_profile_api_profiles__profile_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_api_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_cluster_api_stories__story_id__split_post: {
        parameters: {
            query?: {
                reason?: string | null;
            };
            header?: never;
            path: {
                story_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_digests_api_digests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"][];
                };
            };
        };
    };
    create_digest_api_digests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_api_digests__digest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_digest_api_digests__digest_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_entry_api_digests__digest_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestEntryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_digest_api_digests__digest_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
